### ISSUE TITLE
password creation panel 

### ISSUE THREAD

**Issue by runoono** [Rabu932/PassMan#11]
Instead of a creation panel wouldnt it be better to have a few pop dialogs with textboxes?
![image](https://user-images.githubusercontent.com/16387918/34131286-1053aa7c-e45c-11e7-8572-c0ce13283141.png)

**Comment by runoono** [comment]
or this 
![image](https://user-images.githubusercontent.com/16387918/34131320-289d178a-e45c-11e7-9c44-65fb9d1cc230.png)

**Comment by emirunlu** [comment]
A single popup that contains all required information and forms for a new entry should be ideal.
